export enum OpenWeatherState
{
    ThunderstormWithLightRain = 200,
    ThunderstormWithRain = 201,
    ThunderstormWithHeavyRain = 202,
    ThunderstormLight = 210,
    Thunderstorm = 211,
    ThunderstormHeavy = 212,
    ThunderstormRagged = 221,
    ThunderstormWithLightDrizzle = 230,
    ThunderstormWithDrizzle = 231,
    ThunderstormWithHeavyDrizzle = 232,
    
    DrizzleLightIntensity = 300,
    Drizzle = 301,
    DrizzleHeavyIntensity = 302,
    DrizzleLightIntensityRain = 310,
    DrizzleRain = 311,
    DrizzleHeavyIntensityRain = 312,
    DrizzleAndShowerRain = 313,
    DrizzleAndHeavyShowerRain = 314,
    DrizzleShower = 321,
    
    Rain = 500,
    RainMederate = 501,
    RainHeavyIntensityRain = 502,
    RainVeryHeavyRain = 503,
    RainExtremeRain = 504,
    RainFreezingRain = 511,
    RainLightIntensityShower = 520,
    RainShower = 521,
    RainHeavyIntensityShower = 522,
    RainRaggedShower = 531,
    
    SnowLight = 600,
    Snow = 601,
    SnowHeavy = 602,
    SnowSleet = 611,
    SnowLightShowerSleet = 612,
    SnowShowerSleet = 613,
    SnowLightRain = 615,
    SnowRain = 616,
    SnowLightShower = 620,
    SnowShower = 621,
    SnowHeavyShower = 622,
    
    Mist = 701,
    Smoke = 711,
    Haze = 721,
    DustSandWhirls = 731,
    Fog = 741,
    Sand = 751,
    Dust = 761,
    Ash = 762,
    Squall = 771,
    Tornado = 781,
    
    Clear = 800,
    Clouds0To25 = 801,
    Clouds25To50 = 802,
    Clouds50To85 = 803,
    Clouds85To100 = 804,
}

export const OpenWeatherStateLabels: { [key in OpenWeatherState]: string } = {
    [OpenWeatherState.ThunderstormWithLightRain]: 'weather.thunderstorm-with-light-rain',
    [OpenWeatherState.ThunderstormWithRain]: 'weather.thunderstorm-with-rain',
    [OpenWeatherState.ThunderstormWithHeavyRain]: 'weather.thunderstorm-with-heavy-rain',
    [OpenWeatherState.ThunderstormLight]: 'weather.thunderstorm-light',
    [OpenWeatherState.Thunderstorm]: 'weather.thunderstorm',
    [OpenWeatherState.ThunderstormHeavy]: 'weather.thunderstorm-heavy',
    [OpenWeatherState.ThunderstormRagged]: 'weather.thunderstorm-ragged',
    [OpenWeatherState.ThunderstormWithLightDrizzle]: 'weather.thunderstorm-with-light-drizzle',
    [OpenWeatherState.ThunderstormWithDrizzle]: 'weather.thunderstorm-with-drizzle',
    [OpenWeatherState.ThunderstormWithHeavyDrizzle]: 'weather.thunderstorm-with-heavy-drizzle',
    [OpenWeatherState.DrizzleLightIntensity]: 'weather.drizzle-light-intensity',
    [OpenWeatherState.Drizzle]: 'weather.drizzle',
    [OpenWeatherState.DrizzleHeavyIntensity]: 'weather.drizzle-heavy-intensity',
    [OpenWeatherState.DrizzleLightIntensityRain]: 'weather.drizzle-light-intensity-rain',
    [OpenWeatherState.DrizzleRain]: 'weather.drizzle-rain',
    [OpenWeatherState.DrizzleHeavyIntensityRain]: 'weather.drizzle-heavy-intensity-rain',
    [OpenWeatherState.DrizzleAndShowerRain]: 'weather.drizzle-and-shower-rain',
    [OpenWeatherState.DrizzleAndHeavyShowerRain]: 'weather.drizzle-and-heavy-shower-rain',
    [OpenWeatherState.DrizzleShower]: 'weather.drizzle-shower',
    [OpenWeatherState.Rain]: 'weather.rain',
    [OpenWeatherState.RainMederate]: 'weather.rain-mederate',
    [OpenWeatherState.RainHeavyIntensityRain]: 'weather.rain-heavy-intensity-rain',
    [OpenWeatherState.RainVeryHeavyRain]: 'weather.rain-very-heavy-rain',
    [OpenWeatherState.RainExtremeRain]: 'weather.rain-extreme-rain',
    [OpenWeatherState.RainFreezingRain]: 'weather.rain-freezing-rain',
    [OpenWeatherState.RainLightIntensityShower]: 'weather.rain-light-intensity-shower',
    [OpenWeatherState.RainShower]: 'weather.rain-shower',
    [OpenWeatherState.RainHeavyIntensityShower]: 'weather.rain-heavy-intensity-shower',
    [OpenWeatherState.RainRaggedShower]: 'weather.rain-ragged-shower',
    [OpenWeatherState.SnowLight]: 'weather.snow-light',
    [OpenWeatherState.Snow]: 'weather.snow',
    [OpenWeatherState.SnowHeavy]: 'weather.snow-heavy',
    [OpenWeatherState.SnowSleet]: 'weather.snow-sleet',
    [OpenWeatherState.SnowLightShowerSleet]: 'weather.snow-light-shower-sleet',
    [OpenWeatherState.SnowShowerSleet]: 'weather.snow-shower-sleet',
    [OpenWeatherState.SnowLightRain]: 'weather.snow-light-rain',
    [OpenWeatherState.SnowRain]: 'weather.snow-rain',
    [OpenWeatherState.SnowLightShower]: 'weather.snow-light-shower',
    [OpenWeatherState.SnowShower]: 'weather.snow-shower',
    [OpenWeatherState.SnowHeavyShower]: 'weather.snow-heavy-shower',
    [OpenWeatherState.Mist]: 'weather.mist',
    [OpenWeatherState.Smoke]: 'weather.smoke',
    [OpenWeatherState.Haze]: 'weather.haze',
    [OpenWeatherState.DustSandWhirls]: 'weather.dust-sand-whirls',
    [OpenWeatherState.Fog]: 'weather.fog',
    [OpenWeatherState.Sand]: 'weather.sand',
    [OpenWeatherState.Dust]: 'weather.dust',
    [OpenWeatherState.Ash]: 'weather.ash',
    [OpenWeatherState.Squall]: 'weather.squall',
    [OpenWeatherState.Tornado]: 'weather.tornado',
    [OpenWeatherState.Clear]: 'weather.clear',
    [OpenWeatherState.Clouds0To25]: 'weather.clouds-0-to-25',
    [OpenWeatherState.Clouds25To50]: 'weather.clouds-25-to-50',
    [OpenWeatherState.Clouds50To85]: 'weather.clouds-50-to-85',
    [OpenWeatherState.Clouds85To100]: 'weather.clouds-85-to-100',
}